### ISSUE TITLE
Submit to CRAN

### ISSUE THREAD

**Issue by salvafern** [EMODnet/EMODnetWFS#10]
To be checked:
* R-CMD failing: https://github.com/EMODnet/EMODnetWFS/actions/runs/497401361
* Issue #9

**Comment by salvafern** [comment]
For some reason, the same check that failed during the automatic night check worked after re-running on the morning
https://github.com/EMODnet/EMODnetWFS/actions/runs/516605203

**Comment by maelle** [comment]
I've added a CRAN submission milestone. Should this issue be closed as the CRAN submission would probably use `usethis::use_release_issue()`?
