### ISSUE TITLE
Move master to main

### ISSUE THREAD

**Issue by maelle** [EMODnet/EMODnetWFS#102]
https://www.tidyverse.org/blog/2021/10/renaming-default-branch/

Ok with you @salvafern @annakrystalli?

**Comment by maelle** [comment]
Ok with you @salvafern @annakrystalli?

**Comment by annakrystalli** [comment]
Good with me!

**Comment by salvafern** [comment]
Good with me!

**Comment by maelle** [comment]
However I do not have admin access to this repo which is required for `usethis::git_default_branch_rename()`. Could I be granted admin rights, or could any of you run the function?

**Comment by salvafern** [comment]
I have granted you admin rights
