### ISSUE TITLE
Track package use

### ISSUE THREAD

**Issue by LennertSchepers** [EMODnet/EMODnetWFS#114]
This just came up in the EMODnet Bio meeting, how can we track the use of the package?

E.g. can we use these badges? https://shields.io/category/downloads
![https://img.shields.io/github/downloads/EMODnet/EMODnetWFS/total](https://img.shields.io/github/downloads/EMODnet/EMODnetWFS/total) - [link](https://img.shields.io/github/downloads/EMODnet/EMODnetWFS/total)

Any other ideas on the best way to track usage?

(that there might be an official way that we have to report it, but this issue is to start listing the best/possible ways)

**Comment by annakrystalli** [comment]
Hey @LennertSchepers! I think until the package is on CRAN, there isn't a good option for tracking installation from GitHub (see discussion here: https://github.com/r-lib/devtools/issues/1729).

However, @maelle added a header which at least for now allows tracking the number of connection to the servers made through the package: https://github.com/EMODnet/EMODnetWFS/blob/23f4d9a521cdbad20c69dd94c3524086c8c47615/R/client.R#L32-L39

**Comment by maelle** [comment]
Noting we should probably change the user agent based on an environment variable to mark calls from the package developers differently

**Comment by maelle** [comment]
Does anyone know whether the web service maintainers log user agents of requests?

**Comment by salvafern** [comment]
> Does anyone know whether the web service maintainers log user agents of requests?

@bart-v do we do this for all lots?

**Comment by bart-v** [comment]
By default, most web statics log user agents string, so I would say "yes"

**Comment by maelle** [comment]
Cool, thanks both, that's good to know.

And after #119 the user-agent from this package should be more useful. :grin:

**Comment by maelle** [comment]
Can we close this @salvafern? Or do we first want some confirmation that the user agent that is recorded in the log is "useful"?

**Comment by salvafern** [comment]
Ok for me if also @LennertSchepers @bart-v agree. Is the info in the user agent useful? 

Right now looks like e.g.:
```r
EMODnetWFS:::emodnetwfs_user_agent()
#> [1] "EMODnetWFS R package 2.0.1.9001 https://github.com/EMODnet/EMODnetWFS"
```

**Comment by bart-v** [comment]
Yes, perfect.
The version is dynamic, right?

**Comment by maelle** [comment]
Indeed

https://github.com/EMODnet/EMODnetWFS/blob/bcc10da67b1d4c9e4107b5b5799c954c0f417c3e/R/EMODnetWFS-package.R#L14-L27

It should be different for
- Anna, Salva, me
- GitHub Actions
- other users.

**Comment by maelle** [comment]
(oops I thought you meant the output, not the R package version :woman_facepalming: )
