### ISSUE TITLE
Handling large layers

### ISSUE THREAD

**Issue by brittlnv** [EMODnet/EMODnetWFS#12]
```
# Start client
View(emodnet_wfs)
emodnet_client <- emodnet_init_wfs_client("seabed_habitats_general_datasets_and_products")

# See list of layers available and get Sandbanks of Europe
View(emodnet_get_wfs_info(emodnet_client))
subs <- emodnet_get_layers(emodnet_client, layers = "eusm2019_subs_full", reduce_layers = TRUE)
```

returns error

> Warning: Download of layer 'eusm2019_subs_full' failed: Error in readBin(content, character()): R character strings are limited to 2^31-1 bytes

Is there a way to import such large layers through this package?

**Comment by LennertSchepers** [comment]
I think this is the same issue as https://github.com/EMODnet/EMODnetWFS/issues/1, no solution yet but closing this issue as this is a duplicate :)
