### ISSUE TITLE
Link to WFS endpoints in emodnetwfs.Rmd is broken

### ISSUE THREAD

**Issue by ramiromagno** [EMODnet/EMODnetWFS#141]
I just started out looking into the data made accessible with EMODnetWFS, and I was reading vignette [EMODnetWFS Case Study: Accessing and mapping EMODnet data](https://emodnet.github.io/EMODnetWFS/articles/emodnetwfs.html) and the link:

<https://www.emodnet.eu/en/data>

here

https://github.com/EMODnet/EMODnetWFS/blob/82247f70f4cd13688cc6560ef6da26318c0c016b/vignettes/articles/emodnetwfs.Rmd#L16

seems to be broken.

**Comment by maelle** [comment]
Thanks a lot :pray:

**Comment by ramiromagno** [comment]
Thank you!
