### ISSUE TITLE
`emodnet_get_wfs_info(wfs_bio)` introduced twice

### ISSUE THREAD

**Issue by ramiromagno** [EMODnet/EMODnetWFS#142]
In the README file you present the command:

```
# or you can pass a wfs client object.
emodnet_get_wfs_info(wfs_bio)

# You can also get info for specific layers from wfs object:
emodnet_get_wfs_info(wfs_bio)
(...)
```

twice in succession.

As I was reading the README  I had to double-check to make sure there was not any subtle difference between the two commands. Perhaps you could remove one of the commands?

**Comment by maelle** [comment]
Oops, good catch, thanks a lot @ramiromagno!
