### ISSUE TITLE
Question: Dump all data in one go?

### ISSUE THREAD

**Issue by ramiromagno** [EMODnet/EMODnetWFS#143]
I noticed that some requests, e.g.

```R
wfs_sea02 <- emodnet_init_wfs_client(service = "seabed_habitats_individual_habitat_map_and_model_datasets")
emodnet_get_layer_info(wfs = wfs_sea02, layers = "gb100399")
```

take a few minutes to run.

Is there an alternative way to download these data not via the endpoints, i.e. a way of downloading the whole database in one go?

**Comment by maelle** [comment]
:wave: @ramiromagno! 
What do you mean by the whole database? The data corresponding to your call or more?
Does https://emodnet.ec.europa.eu/geonetwork/emodnet/eng/catalog.search#/metadata/216e5f4f-5142-4eac-a11f-698aa84a6a3a help at all?
Cc @salvafern

**Comment by ramiromagno** [comment]
Hi @maelle !

I mean the raw data behind all those maps provided by the service `"seabed_habitats_individual_habitat_map_and_model_datasets"`, i.e. each map corresponding to each of the available layers for that service.

**Comment by maelle** [comment]
@salvafern @tim-collart do you have any pointer for data dumps?

**Comment by salvafern** [comment]
Hi @ramiromagno 👋

Bit hard to say tbh. I think the best is that you write to secretariat@emodnet.ec.europa.eu to request the raw data. They will be able to point to the responsible person for these data.

**Comment by ramiromagno** [comment]
Hi @salvafern:

Thank you for your suggestion. I will contact the secretariat.
