### ISSUE TITLE
Revisit default wfs service

### ISSUE THREAD

**Issue by annakrystalli** [EMODnet/EMODnetWFS#15]
Currently, the default service if no service is specified in many of the functions is `seabed_habitats_individual_habitat_map_and_model_datasets`. This is somewhat arbitrary and the result of that being the service of interest when I first started working on the package. 

- Should we remove the default value for the service argument? I feel it makes more sense for users to have to be explicit in all cases about the service they want to use and not fall back on any defaults.
- If we do want a default, is another service more sensible?

Let me know your thoughts @salvafern & @LennertSchepers !

**Comment by salvafern** [comment]
I agree with @annakrystalli I think the users should specify always the service.

**Comment by annakrystalli** [comment]
Happy to sort this out if you want?

**Comment by salvafern** [comment]
Sure go ahead! 😄 or let me know if you need to discuss this further.
