### ISSUE TITLE
update example in request-params.Rmd

### ISSUE THREAD

**Issue by maelle** [EMODnet/EMODnetWFS#160]
We have this example code in a pkgdown article

```r
library(EMODnetWFS)

wfs <- emodnet_init_wfs_client("human_activities")

emodnet_get_layers(
  wfs = wfs,
  layers = "maritimebnds",
  featureID = "maritimebnds.861",
  reduce_layers = TRUE
)
```

However "martimebnds" seems to no longer be a layer for this service.

@salvafern I have two questions

- is that "maritimebnds" boundary in another service? Did it just disappear? How would user know about changes in available layers?
- do you know of another example we could use instead in the article. It needs to be a layer with featureIDs (not sure where to find those), a feature we can use to `sortBy`, enough features for `startIndex` to be interesting, `propertyName` to be useful, and it needs geometry to demonstrate filtering by a box. Also how can we choose one that doesn't disappear?

https://github.com/EMODnet/EMODnetWFS/blob/main/vignettes/articles/request-params.Rmd

**Comment by salvafern** [comment]
This layer was temporaly removed from EMODnet due to https://github.com/lifewatch/marineregions-issues/issues/13 - we will update the maritime boundaries product in the next release.

I would say better to not use layers from Human Activities as anything with a political content is more prone to change / disappear. In general layers should not be taken down but I wouldn't be surprised if it happens again without notification. Not sure I have a solution.

I will look for a layer that works as an example

**Comment by maelle** [comment]
@salvafern Friendly reminder :smile_cat:

**Comment by maelle** [comment]
@salvafern any update? :smiley_cat:

**Comment by maelle** [comment]
@salvafern friendly reminder :slightly_smiling_face:

**Comment by salvafern** [comment]
Apologies for overlooking this. I cannot find an example outside human activities, it might be that it is the only lot that uses featureID. 

An example in human activities is the layer "pipelines":

``` r
library(EMODnetWFS)

wfs <- emodnet_init_wfs_client("human_activities")
#> Loading ISO 19139 XML schemas...
#> Loading ISO 19115 codelists...
#> ✔ WFS client created successfully
#> ℹ Service: "https://ows.emodnet-humanactivities.eu/wfs"
#> ℹ Version: "2.0.0"

emodnet_get_layers(
    wfs = wfs,
    layers = "pipelines",
    featureID = "pipelines.1",
    reduce_layers = TRUE
)
#> Simple feature collection with 1 feature and 13 fields
#> Geometry type: MULTILINESTRING
#> Dimension:     XY
#> Bounding box:  xmin: -5.87186 ymin: 35.99551 xmax: -5.836784 ymax: 36.12588
#> Geodetic CRS:  WGS 84
#>        gml_id   id status medium operator size_in length_m year from_loc to_loc
#> 1 pipelines.1 <NA> Active   <NA>     <NA>    <NA> 15467.17 <NA>     <NA>   <NA>
#>   country_co country notes                       the_geom
#> 1         ES   Spain  <NA> MULTILINESTRING ((-5.87186 ...
```

<sup>Created on 2024-06-25 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

I added a new branch and updated the article. But there are other places in the package where the Maritime Boundaries layer is mentioned (vignette EMODnetWFS and one of the test).

**Comment by maelle** [comment]
Thank you!! I removed the example from the main vignette. It's a pity!
