### ISSUE TITLE
! No OGC service found at URL https://geo-service.maris.nl/emodnet_chemistry/wfs

### ISSUE THREAD

**Issue by maelle** [EMODnet/EMODnetWFS#168]
cc @salvafern

**Comment by maelle** [comment]
https://github.com/EMODnet/EMODnetWFS/actions/runs/9457643667/job/26065049365

**Comment by maelle** [comment]
I see no update of https://github.com/EMODnet/Web-Service-Documentation/

**Comment by bart-v** [comment]
That was tonight
The service has restored this morning 2024-06-11T07:00 CET
So there is no issue.

Again, we have an existing monitoring service at http://monitor.emodnet.eu, where you can see the status with only 10min delay, and not half day of delay.

**Comment by maelle** [comment]
ok, thank you!! I actually relaunched the CI build earlier today. I'll look at the monitor next time! :innocent:
