### ISSUE TITLE
Feature attribute metadata?

### ISSUE THREAD

**Issue by annakrystalli** [EMODnet/EMODnetWFS#18]
Hey @salvafern ,

I was just wondering, are metadata on the attributes of each layer available through the server? For  example,  when I download windfarm data:

``` r
library(EMODnetWFS)
emodnet_get_layers(service = "human_activities", layers = "windfarms")
#> Loading ISO 19139 XML schemas...
#> Loading ISO 19115 codelists...
#> ✓ WFS client created succesfully
#> ℹ Service: 'https://ows.emodnet-humanactivities.eu/wfs'
#> ℹ Version: '2.0.0'
#> Warning: crs missing. Set to default 4326
#> $windfarms
#> Simple feature collection with 219 features and 9 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: -16.4 ymin: 27.757 xmax: 25.97 ymax: 65.74
#> Geodetic CRS:  WGS 84
#> First 10 features:
#>           gml_id country n_turbines power_mw     status start  dist_coast notes
#> 1    windfarms.1   Spain          1      5.0 Production  2018  3211.17407  <NA>
#> 2   windfarms.24  France         NA      8.0 Production  2015 10400.68077  <NA>
#> 3  windfarms.190  Greece         NA     24.0    Planned  <NA>  1711.23910  <NA>
#> 4    windfarms.4   Spain          1      4.5 Production  2013    22.36593  <NA>
#> 5   windfarms.58 Denmark         NA    240.0    Planned  <NA>  6518.04614  <NA>
#> 6    windfarms.6   Spain          5     50.0 Production  2017  3211.17407  <NA>
#> 7   windfarms.59 Denmark         NA    160.0    Planned  <NA>  8396.57314  <NA>
#> 8   windfarms.60 Denmark         NA    120.0    Planned  <NA>  7725.66890  <NA>
#> 9   windfarms.63 Denmark         NA    320.0    Planned  <NA>  9328.48812  <NA>
#> 10  windfarms.75  Norway         NA     10.0    Planned  <NA>  9225.51976  <NA>
#>      ljstatus             the_geom
#> 1  production POINT (-15.36 28.04)
#> 2  production POINT (-2.778 47.24)
#> 3     planned  POINT (25.85 40.83)
#> 4  production  POINT (-15.4 27.85)
#> 5     planned  POINT (11.01 55.59)
#> 6  production POINT (-15.36 28.04)
#> 7     planned   POINT (9.82 55.15)
#> 8     planned  POINT (10.41 56.03)
#> 9     planned  POINT (11.11 55.06)
#> 10    planned   POINT (5.01 59.15)
```

<sup>Created on 2021-08-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

How can I get information on for example, what the units `dist_coast` is in?

**Comment by salvafern** [comment]
Hi @annakrystalli

You can get some info about the attributes using a [DescribeFeatureType ](https://docs.geoserver.org/latest/en/user/services/wfs/reference.html#describefeaturetype)request. But this info is very limited, I don't think this is what you are looking for. It seems it is not possible to describe the attributes (at least using geoserver).

> https://ows.emodnet-humanactivities.eu/wfs?service=wfs&request=DescribeFeatureType&version=2.0.0&typeNames=emodnet:windfarms
``` xml
<?xml version="1.0" encoding="UTF-8"?><xsd:schema xmlns:emodnet="www.emodnet.co.uk" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:wfs="http://www.opengis.net/wfs/2.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="www.emodnet.co.uk">
  <xsd:import namespace="http://www.opengis.net/gml/3.2" schemaLocation="https://ows.emodnet-humanactivities.eu/geoserver/schemas/gml/3.2.1/gml.xsd"/>
  <xsd:complexType name="windfarmsType">
    <xsd:complexContent>
      <xsd:extension base="gml:AbstractFeatureType">
        <xsd:sequence>
          <xsd:element maxOccurs="1" minOccurs="0" name="country" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="n_turbines" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="power_mw" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="status" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="start" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="dist_coast" nillable="true" type="xsd:decimal"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="notes" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="ljstatus" nillable="true" type="xsd:string"/>
          <xsd:element maxOccurs="1" minOccurs="0" name="the_geom" nillable="true" type="gml:GeometryPropertyType"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  <xsd:element name="windfarms" substitutionGroup="gml:AbstractFeature" type="emodnet:windfarmsType"/>
</xsd:schema>
```


Although in this specific layer I can see there is some information in the abstract, but of course this is not machine-readable. 

``` r
library(EMODnetWFS)

wfs <- emodnet_init_wfs_client("human_activities")
#> Loading ISO 19139 XML schemas...
#> Loading ISO 19115 codelists...
#> v WFS client created succesfully
#> i Service: 'https://ows.emodnet-humanactivities.eu/wfs'
#> i Version: '2.0.0'

windfarms_info <- emodnet_get_layer_info(wfs, layers = "windfarms")

cat(windfarms_info$abstract)
#> The database on offshore wind farms in the EU was created in 2014 by CETMAR for the European Marine Observation and Data Network (EMODnet). It is the result of the aggregation and harmonization of datasets provided by several sources from all across the EU. It is updated every year, and is available for viewing and download on EMODnet - Human Activities web portal (www.emodnet-humanactivities.eu). The database contains points and/or (where available) polygons representing offshore wind farms in the following countries: Belgium, Denmark, Estonia, Finland, France, Germany, Greece, Ireland, Italy, Latvia, Lithuania, Netherlands, Norway, Poland, Portugal, Spain, Sweden and United Kingdom. Each point has the following attributes (where available): Name, Nº of turbines, Status (Authorised, Operational, Planned, Under Construction), Country, Year, Website, Power (MW), Distance to coast (metres), Perimeter (kilometres), Surface (square kilometres) only for polygons. The distance to coast from polygon centroid or point has been calculated using the Reference Coordinates System with identifier EPSG: 3034 - Single CRS for all Europe (Used for conformal mapping at scales of 1:500,000 and smaller). Compared with the previous version this new version has been updated and reviewed.
```

<sup>Created on 2021-08-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I'll let you know if I learn something else!

**Comment by annakrystalli** [comment]
Thanks @salvafern . I've found the `DescribeFeatureType()` method and written a function in EMODnetWFS to print it (see [`layer_attribute_descriptions()`](https://github.com/EMODnet/EMODnetWFS/blob/52d50cff3303fce0d387bfaaa10d295631cce52c/R/layer_attributes.R#L32) in #17) so users can inspect attributes to help develop appropriate filters. However, it still doesn't give enough detailed information. I would expect at the very least a longer description of each feature attribute, so it is very clear what it is, and units if applicable.  What do you think?


I know the human activities service is not one you manage. But I imagine it's the same for the Biology data?

**Comment by annakrystalli** [comment]
DOH!! Sorry Salva. Just looked more closely and seen that indeed there is useful info (including units) in the abstract. You are right it's not machine readable but at least it is available. I'll have a look at a few more abstracts too. If there is a way to get machine readable info it would indeed be better though.

**Comment by salvafern** [comment]
But of course these descriptions are just free text that someone wrote - so for the wind farms we have the units but there will be cases that won't describe as much. 

In biology we use geoserver to serve data as WFS/WMS etc (see [geo.vliz.be](https://geo.vliz.be/geoserver/web/)). I don't see any option in geoserver to describe the attributes in a more structured way than the abstract. I'll keep looking for ti anyways but it is likely that these descriptions don't exist! 

An alternative would be to print as a `message()` the layer abstract when you load it? Make more obvious to the user what is the dataset they are looking at.

**Comment by salvafern** [comment]
I asked @bart-v and he suggested we could look into geonetwork and CSW (see list of services [in this link](https://emodnet.ec.europa.eu/en/data#inline-nav-1)). But this is probably not completely structured - not machine readable. Not all the EMODnet lots have this service readily available.

**Comment by maelle** [comment]
I think this is related to #72

**Comment by salvafern** [comment]
I think this is done from https://github.com/EMODnet/EMODnetWFS/commit/1d155af02c62d64a4a25f89a7359fd0dce2f04f8 with `layer_attributes_get_names()` and `layer_attribute_inspect()`. Will close for now
