### ISSUE TITLE
Services not available?

### ISSUE THREAD

**Issue by JanJaapPoos** [EMODnet/EMODnetWFS#19]
It seems that some of the services mentioned in the documentation are not available anymore. I cannot get any data from 
seabed_habitats_general_datasets_and_products or seabed_habitats_individual_habitat_map_and_model_datasets. This means that the default  in emodnet_init_wfs_client() also does not work. 

Using v1.0.0 in R3.6.1.

**Comment by salvafern** [comment]
It seems that the WFS endpoints of EMODnet Seabed Habitats have changed:

- `https://ows.emodnet-seabedhabitats.eu/emodnet_open/wfs` -> `https://ows.emodnet-seabedhabitats.eu/geoserver/emodnet_open/wfs`

- `https://ows.emodnet-seabedhabitats.eu/emodnet_open_maplibrary/wfs` -> `https://ows.emodnet-seabedhabitats.eu/geoserver/emodnet_open_maplibrary/wfs`

I'll update them. Thank you @JanJaapPoos for notifying!

**Comment by annakrystalli** [comment]
Hey @salvafern 

While the endpoints seem to connect ok, they don't seem to be returning any data?

``` r
library(EMODnetWFS)
emodnet_get_layers(service = "seabed_habitats_individual_habitat_map_and_model_datasets",
                   layers = c("dk003069", "dk003070"))
#> Loading ISO 19139 XML schemas...
#> Loading ISO 19115 codelists...
#> ✓ WFS client created succesfully
#> ℹ Service: 'https://ows.emodnet-seabedhabitats.eu/geoserver/emodnet_open_maplibrary/wfs'
#> ℹ Version: '2.0.0'
```

<sup>Created on 2021-09-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
