### ISSUE TITLE
Check using crs during query

### ISSUE THREAD

**Issue by annakrystalli** [EMODnet/EMODnetWFS#2]

**Comment by LennertSchepers** [comment]
I mentioned that it might be worth checking for the coordinate reference systems (CRS) that the WFS can return.
However, apparently not all possible CRSes are listed in the *WFS* GetCapabilities request.
See for example the explanation here: https://docs.geoserver.org/stable/en/user/services/wfs/webadmin.html#configuring-additional-srs

I was actually thinking about the a *WMS* GetCapabilities request, where you can see all available CRSes, see for example here: https://ows.emodnet-seabedhabitats.eu/emodnet_open_maplibrary/wms?request=GetCapabilities&service=WMS (look for all the CRSes between `<CRS></CRS>`)

So it might be possible that all CRSes mentioned in the *WMS* GetCapabilities can be used for the *WFS* request, but I'm not sure.

This seems also relevant:  https://gis.stackexchange.com/a/129912/44980

**Comment by annakrystalli** [comment]
Related request from Britt?:

> Apart from this, it would maybe also be useful for users to not only inspect the available layers from the GetCapabilities output, but to get the opportunity to gain more insight into the layers by adding a DescribeFeatureType request? I don’t know if that would be feasible to you, but it seems like this would really make it an all-round package.

**Comment by annakrystalli** [comment]
I tried to play around with WMS briefly but couldn't seem to get that far. I'll try an put a demo of what I tried together.

**Comment by maelle** [comment]
What's the status on this @annakrystalli?

**Comment by salvafern** [comment]
> Related request from Britt?:
> 
> > Apart from this, it would maybe also be useful for users to not only inspect the available layers from the GetCapabilities output, but to get the opportunity to gain more insight into the layers by adding a DescribeFeatureType request? I don’t know if that would be feasible to you, but it seems like this would really make it an all-round package.

This is tackled in https://github.com/EMODnet/EMODnetWFS/issues/18

**Comment by salvafern** [comment]
I can see:

1. The default CRS is actually checked: https://github.com/EMODnet/EMODnetWFS/blob/main/R/layer_attributes.R#L199 and used when requesting the layer.
2. If a different CRS is requested, the transformation occurs on the client side: https://github.com/EMODnet/EMODnetWFS/blob/main/R/layers.R#L182
