### ISSUE TITLE
assumption on CRS when downloading data from geology_seabed_substrate_maps  

### ISSUE THREAD

**Issue by JanJaapPoos** [EMODnet/EMODnetWFS#20]
When downloading seabed substrate data from geology_seabed_substrate_maps , the CRS is not provided by the server. The CRS is then assumed to be 4326. This is incorrect. 

wfs <- emodnet_init_wfs_client(service="geology_seabed_substrate_maps")
test <- emodnet_get_layers(wfs = wfs, layers = "seabed_substrate_1m", reduce_layers = T)

gives: Warning: crs missing. Set to default 4326

Working from the assumption that it is 3857 also yields incorrect maps, so I am a bit at a loss at what the correct CRS is.

version 1.0.0 in R3.6.1

**Comment by annakrystalli** [comment]
Thank you for reporting this! Will look into this asap.

**Comment by annakrystalli** [comment]
This should now be working correctly and downloading the layer with `epsg: 3034`. Thanks again for spotting. That was a major bug that definitely needed fixing! Let me know if you are still having problems.
