### ISSUE TITLE
Improve communication of service status to users

### ISSUE THREAD

**Issue by annakrystalli** [EMODnet/EMODnetWFS#24]
I feel we need good communication channels set up with service maintainers to be able to quickly figure out whether problems are from bugs in the package or service issues.

We should discuss at the next meeting.

I think at the very least a list of contact details for each service is necessary but would be interesting to explore whether there are better options.

**Comment by salvafern** [comment]
Hi @tim-collart and @bart-v , do you know if there is any mail list of EMODnet that could we use to know when new services are added or edited?
