### ISSUE TITLE
Separate service testing from package testing and only report package testing result on README.

### ISSUE THREAD

**Issue by annakrystalli** [EMODnet/EMODnetWFS#26]
It feels like a lot of the failing tests recently relate more to failing services. While I'm glad we are testing them (and look forward to implementing during runtime too as discussed in #24 ), I feel it's not appropriate for our build to be showing as failing when it's services that are the issue.

The best way to implement it might well be separating service testing into a different GitHub Action. What do you think @salvafern ?

**Comment by maelle** [comment]
What remains to be done here? httptest is now used.
