### ISSUE TITLE
Example of using BBOX() in cql_filter argument in emodnet_get_layers

### ISSUE THREAD

**Issue by JanJaapPoos** [EMODnet/EMODnetWFS#27]
Hi,

I wonder if it is possible to crop data when requesting a layer from a service. 

Looking at the documentation there is a bbox(expr, num, num, num, num) that can be used in cql_filter, but I wonder what expr to provide if I want to crop the entire layer. Is this even possible? If so I think it would be helpful to add to the vignette about cql_filter().

Thanks once more for your work, 

Jan Jaap

**Comment by annakrystalli** [comment]
Hello @JanJaapPoos ! ☺️

Indeed you can use the bbox filet like so:

```r
emodnet_get_layers(service = "geology_seabed_substrate_maps", 
                   layers = "seabed_substrate_1m",
                   cql_filter = "BBOX(geom, 2565427, 4026324, 1522239, 2778536)",
                   reduce_layers = TRUE ) 
```

Note that coordinates are supplied in the sequence **`xmin`, `xmax`, `ymin`, `ymax`** and the query default is to use the CRS of the queried layer unless an additional CRS argument is provided. See more detail here https://docs.geoserver.org/latest/en/user/filter/ecql_reference.html#spatial-predicate.

I'll also be updating the docs with much more detailed documentation shortly.

**Comment by JanJaapPoos** [comment]
Hi @annakrystalli, 

Excellent, thanks.

**Comment by salvafern** [comment]
Hey @annakrystalli!

I wonder if providing a CRS via the crs argument would actually work since the CQL filter is applied in the WFS request but the reprojection is performed in the client side?

https://github.com/EMODnet/EMODnetWFS/blob/1d170d5bde0a4bd8ddbf2398f284e12d4fe3f838/R/layers.R#L135

For that to work I think the reprojection would have to be requested with WFS instead of using sf. What do you think? 😶

**Comment by annakrystalli** [comment]
Hey @salvafern. When you use the bbox predicate, you can supply a CRS which refers to the CRS the bbox coordinates which could differ from the CRS the layers are in as part of the cql_filter. It's completely separate to the `crs` argument.

**Comment by salvafern** [comment]
Ah ok good, didn't know! Thanks @annakrystalli
