### ISSUE TITLE
Add EMODnet Chemistry contaminants WFS

### ISSUE THREAD

**Issue by annakrystalli** [EMODnet/EMODnetWFS#3]
From Britt:

> As far as I can tell, there is only one (relatively recent) web service missing, namely that of the EMODnet Chemistry contaminants (URL: https://nodc.inogs.it/geoserver/Contaminants/wfs). It would be nice if you could also include this in the package J

**Comment by maelle** [comment]
@annakrystalli the service is listed with the URL https://nodc.ogs.trieste.it/geoserver/Contaminants/wfs

- which URL is correct?
- can we close this issue?

**Comment by maelle** [comment]
@salvafern this is something the discussion in #129 could help with

**Comment by maelle** [comment]
We're currently getting an error for this web service. @bart-v is it a known problem? What is the official URL of the service? 

```r
Error in names(namespaces) <- rep("", length(namespaces)) : 
  attempt to set an attribute on NULL
Backtrace:
  1. EMODnetWFS::emodnet_get_wfs_info(service = "chemistry_contaminants")
  5. EMODnetWFS (local) `<fn>`(service = "chemistry_contaminants")
  7. EMODnetWFS::emodnet_init_wfs_client(service)
 10. ows4R::WFSClient$new(...)
 11. ows4R (local) initialize(...)
     ...
 13. ows4R (local) initialize(...)
 14. private$fetchFeatureTypes(xmlObj, version)
 15. XML::getNodeSet(xmlObj, "//ns:FeatureType", wfsNs)
 17. XML:::xpathApply.XMLInternalDocument(...)
 18. XML::matchNamespaces(doc, namespaces)
```

**Comment by salvafern** [comment]
Quick chat with @bart-v : the most authoritative source for WFS is still https://github.com/EMODnet/Web-Service-Documentation/, so the endpoint at the moment would be https://geoserver.hcmr.gr/geoserver/EMODNET_SHARED/wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0 

We should update `emodnet_wfs()` 

relates to #139
