### ISSUE TITLE
Create an overview of all the data?

### ISSUE THREAD

**Issue by maelle** [EMODnet/EMODnetWFS#50]
I.e. a searchable table of all services & layers, e.g. as a regularly updated article in the pkgdown website.

**Comment by maelle** [comment]
Rather have a function (memoise it)

**Comment by annakrystalli** [comment]
We have function [`emodnet_get_all_wfs_info `](https://emodnet.github.io/EMODnetWFS/reference/emodnet_get_wfs_info.html) but yeah, would be great to cache the results daily
