### ISSUE TITLE
add message for download?

### ISSUE THREAD

**Issue by maelle** [EMODnet/EMODnetWFS#53]

**Comment by maelle** [comment]
I think it'd have to be a feature request for ows4R https://github.com/eblondel/ows4R/wiki#wfs-getfeature

**Comment by maelle** [comment]
Maybe a message instead!

**Comment by maelle** [comment]
https://github.com/eblondel/ows4R/issues/72

**Comment by eblondel** [comment]
@maelle For this You can set the `logger = INFO` as argument of https://github.com/EMODnet/EMODnetWFS/blob/23f4d9a521cdbad20c69dd94c3524086c8c47615/R/client.R#L33

**Comment by maelle** [comment]
@annakrystalli @salvafern what do you think of the example in https://github.com/eblondel/ows4R/issues/72#issuecomment-1115871528?

We could set an argument verbose or so (that'd also listen to an option, and that if FALSE would also shut up usethis).

**Comment by eblondel** [comment]
Note that if you set 'DEBUG' instead of 'INFO', R will be more verbose and will display you curl logs

**Comment by salvafern** [comment]
Yes I have used this before :) maybe just leave the user decide the level of verbose? and INFO by default seems good.
