### ISSUE TITLE
How to use cql

### ISSUE THREAD

**Issue by maelle** [EMODnet/EMODnetWFS#54]
- If I remember correctly it was not supported on all services?
- I think #49 is due to my using a wrong cql, should there be some try/catch somewhere?
- How to know what variables a layer has and what values they take? It does not seem `emodnet_get_layer_info()` has that info so what kind of call could help with that?

**Comment by annakrystalli** [comment]
But yes, error handling definitely needs to be improved on this!

**Comment by maelle** [comment]
For characters would there be a way to get a list of possible values, or an excerpt thereof, in the summary? https://emodnet.github.io/EMODnetWFS/articles/eqcl_filtering.html#layer-attribute-summaries
