### ISSUE TITLE
Use fledge?

### ISSUE THREAD

**Issue by maelle** [EMODnet/EMODnetWFS#55]
https://fledge.cynkra.com/dev/

**Comment by maelle** [comment]
I've started using the conventional commits syntax in PR titles in any case (fledge can use that) :grin: https://www.conventionalcommits.org/en/v1.0.0/

**Comment by salvafern** [comment]
I was not aware of this! I'll use it when committing 😄

**Comment by maelle** [comment]
In PRs, you can still make less informative commits, as long as the PR title uses the convention, and as long as you _squash and merge_ it.

I do this all the time as my PR commits tend to be "progress" and "oops". :sweat_smile: 

https://twitter.com/grrrck/status/1108031633750478849
