### ISSUE TITLE
Product story for EMODnet as a vignette

### ISSUE THREAD

**Issue by salvafern** [EMODnet/EMODnetWFS#6]
Hi @annakrystalli ! 

I have written a vignette on how to use this package with some more examples. The idea is to use it as a product story, but I figured it would be good to include it in the package itself. 

Could you please add a short introduction paragraph? 
https://github.com/EMODnet/EMODnetWFS/blob/f9774fa2639be5661e24ac4810a569e747bf92e9/vignettes/emodnetwfs.Rmd#L17

And of course let me know if there is anything you want to change/improve/suggestions etc 😊

**Comment by annakrystalli** [comment]
Working on this atm! BTW, is it ok with you @salvafern if I add the intro directly on your branch (`vignette-story`)? Or do you want me to make a pull request onto your branch?

**Comment by salvafern** [comment]
No problem, add it directly to the `vignette-story` branch 😃
