### ISSUE TITLE
Layer that is a data.frame

### ISSUE THREAD

**Issue by maelle** [EMODnet/EMODnetWFS#62]
``` r
library("EMODnetWFS")
wfs <- emodnet_init_wfs_client(service = "biology_occurrence_data")
#> Loading ISO 19139 XML schemas...
#> Loading ISO 19115 codelists...
#> Loading IANA mime types...
#> No encoding supplied: defaulting to UTF-8.
#> ✓ WFS client created succesfully
#> ℹ Service: 'http://geo.vliz.be/geoserver/Dataportal/wfs'
#> ℹ Version: '2.0.0'
simple_filter_sf <- emodnet_get_layers(
    wfs = wfs,
    layers = "taxa",
    cql_filter = "scientificname='Abra'",
    reduce_layers = TRUE
)
#> Warning: Download of layer 'taxa' failed: Error in UseMethod("st_crs<-"): pas de méthode pour 'st_crs<-' applicable pour un objet de classe "data.frame"
```

<sup>Created on 2022-03-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by maelle** [comment]
@annakrystalli for a change would you like to try running this one? :sweat_smile:

**Comment by maelle** [comment]
the layer type in the layer medata from wfs info was sf, should it indicate something else?

**Comment by maelle** [comment]
I see "sf" is hard-coded, maybe I can get it from the web service :eyes:

**Comment by maelle** [comment]
I modified ows4R code 

https://github.com/eblondel/ows4R/blob/8068e7284e3c0c99f54457579602bc33174f134d/R/WFSFeatureType.R#L328

to `quiet = FALSE`

I get

```
no simple feature geometries present: returning a data.frame or tbl_df
```

**Comment by maelle** [comment]
I wonder whether we should expect more metadata before the download.

**Comment by maelle** [comment]
So, TODOS

- [ ] Find more info on data.frame layers in WFS in general.
- [ ] Tweak the code so that we simply return the data.frame when that's what was returned by the web service.

**Comment by annakrystalli** [comment]
> And when we do get a data.frame, the layers can obviously NOT be reduced.

That's ok because the function only tries to reduce and if it can't it returns a list

**Comment by maelle** [comment]
https://geo.vliz.be/geoserver/Dataportal/wfs?SERVICE=WFS&REQUEST=DescribeFeatureType&VERSION=2.0.0 does not have info that it's a table

**Comment by maelle** [comment]
Related https://github.com/eblondel/ows4R/issues/65

**Comment by maelle** [comment]
For any layer if we get its description and see no element is a geometry, we can know it will be a data.frame rather than an sf object.

**Comment by salvafern** [comment]
I think @maelle 's approach in https://github.com/eblondel/ows4R/issues/65#issuecomment-1065134404 would be great. There are layers in there with no geometry as they are required or used in the infrastructure of EMODnet-Biology, so we cannot really get rid of them.

In any case I will check why some layers don't have a geometry. For instance Dataportal:eurobis-obisenv_basic. Probably someone just forgot as the important fields when exporting to csv are decimalLongitude and decimalLatitude.

**Comment by maelle** [comment]
@salvafern #83 is meant to tackle this.

**Comment by maelle** [comment]
@salvafern My main problem in #83 is the size of fixtures. So if you can have a look at the functionality, that'd be great, I can keep thinking about the testing.
