### ISSUE TITLE
Could the function names clarify which ones perform an HTTP request?

### ISSUE THREAD

**Issue by maelle** [EMODnet/EMODnetWFS#64]

**Comment by maelle** [comment]
@annakrystalli I was thinking about this whilst adding fixtures. It'd be nice to know at a glance which ones recycle info from say the client, and which ones don't.

**Comment by maelle** [comment]
I have been thinking about this again.

- keeping get for the method that just extract metadata
- having "download" in the name of https://emodnet.github.io/EMODnetWFS/reference/emodnet_get_layers.html

**Comment by maelle** [comment]
@annakrystalli @salvafern what's your take on this?

**Comment by maelle** [comment]
Related #53

**Comment by salvafern** [comment]
Hi, I'm not aware of the best practices but seems like a valid point. Other packages use "download" instead of "get" indeed.

**Comment by maelle** [comment]
I was inspired by the [Art of Readable Code](https://www.goodreads.com/book/show/8677004-the-art-of-readable-code) where they wrote "Many Programmers are used to the convention that methods starting with get are 'lightweight accessors' that simply return an internal member."

But maybe we should follow ows4R lead to not confuse users :thinking:

**Comment by salvafern** [comment]
Well if you think it will improve the code readability I am all in!

**Comment by maelle** [comment]
Notes

- Even if creating the client beforehand, `emodnet_get_wfs_info()` needs an internet connection because of `guess_layer_format()`.

**Comment by maelle** [comment]
* `emodnet_get_layer_info()` also performs a query.
