### ISSUE TITLE
Is this package listed on the EMODnet website?

### ISSUE THREAD

**Issue by maelle** [EMODnet/EMODnetWFS#73]
If no, whom do we ask?

It should also be listed in the docs of all web services.

**Comment by salvafern** [comment]
Hi @maelle 

The package is listed as a data product: https://www.emodnet-biology.eu/data-catalog?module=dataset&dasid=6654

**Comment by maelle** [comment]
Thank you!

What about the docs of web services? If someone goes there, it'd be nice for them to see there's an R package to access web services.

**Comment by annakrystalli** [comment]
Hey @salvafern , agree with @maelle . Just been to https://emodnet.ec.europa.eu/en/emodnet-web-service-documentation docs and, while there is a link to an R tutorial in Binder (currently 503 error https://mybinder.org/v2/gh/EMODnet/Web-Service-Documentation/main?urlpath=lab/tree/R-tutorial/index.ipynb), this does not include any mention of the package or link to the documentation. I feel a mention of the package with links to the package docs and repo would be perfectly placed there :)

**Comment by annakrystalli** [comment]
Awesome! Thanks @salvafern !

**Comment by maelle** [comment]
@salvafern thank you! Will you do the PR there?

**Comment by salvafern** [comment]
Yes I will!

**Comment by maelle** [comment]
Thank you! :pray:
