### ISSUE TITLE
Move vignettes to articles

### ISSUE THREAD

**Issue by annakrystalli** [EMODnet/EMODnetWFS#79]

**Comment by maelle** [comment]
Actually for rOpenSci peer-review we might want to keep one vignette, but pre-build it? https://ropensci.org/blog/2019/12/08/precompute-vignettes/

**Comment by maelle** [comment]
@annakrystalli I think we'll still need one real, pre-built, vignette, for submission to rOpenSci. (sorry for the back and forth on this)

**Comment by annakrystalli** [comment]
Doh! Of course. Ok no worries. How simple do you reckon we could keep it to meet the requirement?

**Comment by annakrystalli** [comment]
Working on docs atm @maelle. Am considering adding a very lightweight getting started article which could act as the vignette too? One thing I'm still generally unsure of. What is the difference in purpose of the README (which automatically appears as the landing page of the `pkgdown` site) and a Getting Started vignette in your opinion?

**Comment by maelle** [comment]
A lightweight getting started vignette would be ideal.

I agree that they can be very similar but thankfully one can re-use fragments :tada: https://www.garrickadenbuie.com/blog/dry-vignette-and-readme/
