### ISSUE TITLE
Use EMODnetWFS as backbone of eurobis R package

### ISSUE THREAD

**Issue by salvafern** [EMODnet/EMODnetWFS#86]
Hi all!

I am working a major update of the eurobis R package: https://github.com/lifewatch/eurobis/issues/12. Despite of the name, this package uses the EMODnet-Biology webservices to access the eurobis occurrence data that flows to EMODnet-Biology. 

At the moment, it seems more interesting for me to use ows4r than EMODnetWFS as there are a number of features that are present in ows4r that we need for this sort of package:
* Filters with viewParams (unique of geoserver - not OGC)
* Pagination
* Parallelization

I will also appreciate caching, although this is not yet in ows4r.

I was wondering if you think it is useful to add these features to EMODnetWFS, or maybe we should rather keep this one simpler and use ows4r as backbone of eurobis?

**Comment by maelle** [comment]
Naive question: should the package name be changed to clarify the intent?

**Comment by salvafern** [comment]
> Naive question: should the package name be changed to clarify the intent?

Answered via email

**Comment by maelle** [comment]
Would it make sense to open an issue for each of the specific features @salvafern?

**Comment by salvafern** [comment]
Yes, would :) I'll open them when necessary. For now we can pass any params to ows4R (#87) so it is good enough for me. I'll close for now. Thanks @maelle @annakrystalli !

**Comment by maelle** [comment]
Thank you!
